/* ==========================================================================
   AXZ sim — sound, synthesised rather than sampled.

   Why not a sound pack. A jet's noise is a continuous function of N1, airspeed
   and how much air is going through the fan; a looped sample is one operating
   point stretched over all of them, and the seam is audible the moment you
   move the thrust lever. Everything here is generated by Web Audio and driven
   by the same state the flight model already computes, so spooling up actually
   sounds like spooling up and the airflow rises with indicated airspeed.

   It also keeps the page honest. Downloadable packs come with licences to
   track and megabytes to ship on a page whose whole engine is 180 KB, and this
   is a few hundred lines of oscillators.

   Everything is behind an explicit toggle and starts muted-until-gesture,
   because a page that makes noise on load is a page people close.
   ========================================================================== */

import { clamp } from './math.js'

/** Steady band-limited noise, generated once and looped. */
function noiseBuffer(ctx, seconds = 2) {
  const n = Math.floor(ctx.sampleRate * seconds)
  const buf = ctx.createBuffer(1, n, ctx.sampleRate)
  const d = buf.getChannelData(0)
  // Pink-ish: white through a cheap one-pole, which sits far better under a
  // jet than flat white noise does.
  let last = 0
  for (let i = 0; i < n; i++) {
    const w = Math.random() * 2 - 1
    last = (last + 0.02 * w) / 1.02
    d[i] = last * 3.5
  }
  return buf
}

export class Sound {
  constructor() {
    this.ready = false
    this.enabled = false
    this.ctx = null
    this.master = null
  }

  /**
   * Must be called from a user gesture. Browsers will not start an AudioContext
   * any other way, and this one is started from the same press that downloads
   * the engine.
   */
  init() {
    if (this.ctx) return true
    const AC = window.AudioContext || window.webkitAudioContext
    if (!AC) return false
    try {
      const ctx = new AC()
      this.ctx = ctx
      this.master = ctx.createGain()
      this.master.gain.value = 0
      // A limiter on the bus: an explosion plus a stall horn plus full thrust
      // can otherwise clip, and clipping sounds like a broken page.
      const comp = ctx.createDynamicsCompressor()
      comp.threshold.value = -10
      comp.knee.value = 18
      comp.ratio.value = 8
      comp.attack.value = 0.004
      comp.release.value = 0.22
      this.master.connect(comp)
      comp.connect(ctx.destination)

      this.noise = noiseBuffer(ctx, 3)
      this.buildEngine()
      this.buildAir()
      this.buildWarnings()
      this.ready = true
      return true
    } catch (e) {
      this.ready = false
      return false
    }
  }

  /* --- Engine -------------------------------------------------------------
     Three layers, because a turbofan is three noises: the fan whine (a tone
     an octave or so up, tracking N1), the core rumble (a low tone), and the
     jet itself (broadband noise through a lowpass that opens with thrust). */
  buildEngine() {
    const ctx = this.ctx
    this.eng = {}

    const g = ctx.createGain(); g.gain.value = 0
    g.connect(this.master)
    this.eng.out = g

    const fan = ctx.createOscillator()
    fan.type = 'sawtooth'
    fan.frequency.value = 90
    const fanF = ctx.createBiquadFilter()
    fanF.type = 'bandpass'; fanF.frequency.value = 900; fanF.Q.value = 3.2
    const fanG = ctx.createGain(); fanG.gain.value = 0.16
    fan.connect(fanF); fanF.connect(fanG); fanG.connect(g)
    fan.start()
    this.eng.fan = fan; this.eng.fanF = fanF; this.eng.fanG = fanG

    // A second, slightly detuned fan. Two engines are never exactly in phase,
    // and the beat between them is most of what makes it sound like an
    // aeroplane rather than a synthesiser.
    const fan2 = ctx.createOscillator()
    fan2.type = 'sawtooth'
    fan2.frequency.value = 91.7
    const fan2G = ctx.createGain(); fan2G.gain.value = 0.10
    fan2.connect(fanF); fan2.connect(fan2G); fan2G.connect(g)
    fan2.start()
    this.eng.fan2 = fan2

    const core = ctx.createOscillator()
    core.type = 'triangle'
    core.frequency.value = 46
    const coreG = ctx.createGain(); coreG.gain.value = 0.30
    core.connect(coreG); coreG.connect(g)
    core.start()
    this.eng.core = core; this.eng.coreG = coreG

    const jet = ctx.createBufferSource()
    jet.buffer = this.noise; jet.loop = true
    const jetF = ctx.createBiquadFilter()
    jetF.type = 'lowpass'; jetF.frequency.value = 500; jetF.Q.value = 0.7
    const jetG = ctx.createGain(); jetG.gain.value = 0.5
    jet.connect(jetF); jetF.connect(jetG); jetG.connect(g)
    jet.start()
    this.eng.jetF = jetF; this.eng.jetG = jetG
  }

  /** Airflow over the hull, plus the rumble of wheels on concrete. */
  buildAir() {
    const ctx = this.ctx
    const g = ctx.createGain(); g.gain.value = 0
    g.connect(this.master)

    const src = ctx.createBufferSource()
    src.buffer = this.noise; src.loop = true
    const f = ctx.createBiquadFilter()
    f.type = 'bandpass'; f.frequency.value = 700; f.Q.value = 0.5
    src.connect(f); f.connect(g)
    src.start()
    this.air = { out: g, filter: f }

    const rg = ctx.createGain(); rg.gain.value = 0
    rg.connect(this.master)
    const rsrc = ctx.createBufferSource()
    rsrc.buffer = this.noise; rsrc.loop = true
    const rf = ctx.createBiquadFilter()
    rf.type = 'lowpass'; rf.frequency.value = 160; rf.Q.value = 1.1
    rsrc.connect(rf); rf.connect(rg)
    rsrc.start()
    this.roll = { out: rg, filter: rf }
  }

  /** Stall warning and overspeed clacker, both gated by the flight model. */
  buildWarnings() {
    const ctx = this.ctx
    const g = ctx.createGain(); g.gain.value = 0
    g.connect(this.master)
    const o = ctx.createOscillator()
    o.type = 'square'; o.frequency.value = 780
    const og = ctx.createGain(); og.gain.value = 0.08
    o.connect(og); og.connect(g); o.start()
    this.warn = { out: g }
    this.warnPhase = 0
    this.clackPhase = 0
  }

  setEnabled(on) {
    this.enabled = on
    if (!this.ready) return
    if (on && this.ctx.state === 'suspended') this.ctx.resume()
    const t = this.ctx.currentTime
    this.master.gain.cancelScheduledValues(t)
    this.master.gain.setTargetAtTime(on ? 0.85 : 0, t, 0.08)
  }

  /** One-shot helpers ---------------------------------------------------- */
  blip(freq, dur, type = 'sine', gain = 0.2) {
    if (!this.ready || !this.enabled) return
    const ctx = this.ctx, t = ctx.currentTime
    const o = ctx.createOscillator(), g = ctx.createGain()
    o.type = type; o.frequency.setValueAtTime(freq, t)
    g.gain.setValueAtTime(0, t)
    g.gain.linearRampToValueAtTime(gain, t + 0.008)
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur)
    o.connect(g); g.connect(this.master)
    o.start(t); o.stop(t + dur + 0.02)
  }

  /** Wheels meeting concrete. Scaled by how hard the arrival was. */
  touchdown(fpm) {
    if (!this.ready || !this.enabled) return
    const ctx = this.ctx, t = ctx.currentTime
    const hard = clamp(fpm / 700, 0.12, 1.6)
    const src = ctx.createBufferSource()
    src.buffer = this.noise
    const f = ctx.createBiquadFilter()
    f.type = 'lowpass'
    f.frequency.setValueAtTime(120 + hard * 900, t)
    f.frequency.exponentialRampToValueAtTime(90, t + 0.35)
    const g = ctx.createGain()
    g.gain.setValueAtTime(0, t)
    g.gain.linearRampToValueAtTime(0.5 * hard, t + 0.012)
    g.gain.exponentialRampToValueAtTime(0.0001, t + 0.45)
    src.connect(f); f.connect(g); g.connect(this.master)
    src.start(t, Math.random() * 2, 0.6)
    // The thud under it.
    const o = ctx.createOscillator(), og = ctx.createGain()
    o.type = 'sine'
    o.frequency.setValueAtTime(70, t)
    o.frequency.exponentialRampToValueAtTime(34, t + 0.28)
    og.gain.setValueAtTime(0, t)
    og.gain.linearRampToValueAtTime(0.42 * hard, t + 0.01)
    og.gain.exponentialRampToValueAtTime(0.0001, t + 0.4)
    o.connect(og); og.connect(this.master)
    o.start(t); o.stop(t + 0.45)
  }

  /** Servo whine for gear and flaps. */
  servo(up) {
    if (!this.ready || !this.enabled) return
    const ctx = this.ctx, t = ctx.currentTime
    const o = ctx.createOscillator(), g = ctx.createGain()
    o.type = 'sawtooth'
    o.frequency.setValueAtTime(up ? 220 : 300, t)
    o.frequency.linearRampToValueAtTime(up ? 300 : 210, t + 1.1)
    const f = ctx.createBiquadFilter()
    f.type = 'bandpass'; f.frequency.value = 900; f.Q.value = 5
    g.gain.setValueAtTime(0, t)
    g.gain.linearRampToValueAtTime(0.09, t + 0.12)
    g.gain.setValueAtTime(0.09, t + 0.9)
    g.gain.exponentialRampToValueAtTime(0.0001, t + 1.25)
    o.connect(f); f.connect(g); g.connect(this.master)
    o.start(t); o.stop(t + 1.3)
  }

  /* --- Explosion ----------------------------------------------------------
     A crack, a body of broadband noise sweeping down, and a sub-bass thump
     that arrives with it. Then a tail of crackle. */
  explosion(energy = 1) {
    if (!this.ready || !this.enabled) return
    const ctx = this.ctx, t = ctx.currentTime
    const E = clamp(energy, 0.4, 1.8)

    const src = ctx.createBufferSource()
    src.buffer = this.noise
    const f = ctx.createBiquadFilter()
    f.type = 'lowpass'
    f.frequency.setValueAtTime(5200, t)
    f.frequency.exponentialRampToValueAtTime(150, t + 1.6)
    const g = ctx.createGain()
    g.gain.setValueAtTime(0, t)
    g.gain.linearRampToValueAtTime(0.95 * E, t + 0.012)
    g.gain.exponentialRampToValueAtTime(0.0001, t + 2.2)
    src.connect(f); f.connect(g); g.connect(this.master)
    src.start(t, Math.random(), 2.4)

    const sub = ctx.createOscillator(), sg = ctx.createGain()
    sub.type = 'sine'
    sub.frequency.setValueAtTime(88, t)
    sub.frequency.exponentialRampToValueAtTime(24, t + 1.1)
    sg.gain.setValueAtTime(0, t)
    sg.gain.linearRampToValueAtTime(0.85 * E, t + 0.02)
    sg.gain.exponentialRampToValueAtTime(0.0001, t + 1.5)
    sub.connect(sg); sg.connect(this.master)
    sub.start(t); sub.stop(t + 1.6)

    // Crackle: a scatter of short bursts over the next couple of seconds.
    for (let i = 0; i < 14; i++) {
      const dt = 0.25 + Math.random() * 2.0
      const cs = ctx.createBufferSource()
      cs.buffer = this.noise
      const cf = ctx.createBiquadFilter()
      cf.type = 'bandpass'; cf.frequency.value = 700 + Math.random() * 2600; cf.Q.value = 2
      const cg = ctx.createGain()
      cg.gain.setValueAtTime(0, t + dt)
      cg.gain.linearRampToValueAtTime(0.10 * E, t + dt + 0.006)
      cg.gain.exponentialRampToValueAtTime(0.0001, t + dt + 0.16)
      cs.connect(cf); cf.connect(cg); cg.connect(this.master)
      cs.start(t + dt, Math.random() * 2, 0.2)
    }
  }

  /* --- Per-frame ----------------------------------------------------------
     Everything continuous is a setTargetAtTime toward the value the physics
     just produced. Instant assignment would zipper. */
  update(ac, dt, cameraInside) {
    if (!this.ready || !this.enabled) return
    const ctx = this.ctx, t = ctx.currentTime
    const tc = 0.09

    // Engine. N1 is the spooled state, so the sound lags the lever exactly as
    // the thrust does.
    const n1 = clamp(ac.thrustLag, 0, 1)
    const inside = cameraInside ? 1 : 0
    const fanHz = 78 + n1 * 168
    this.eng.fan.frequency.setTargetAtTime(fanHz, t, tc)
    this.eng.fan2.frequency.setTargetAtTime(fanHz * 1.019, t, tc)
    this.eng.core.frequency.setTargetAtTime(38 + n1 * 54, t, tc)
    this.eng.fanF.frequency.setTargetAtTime(620 + n1 * 1500, t, tc)
    this.eng.jetF.frequency.setTargetAtTime(240 + n1 * 2100, t, tc)
    this.eng.jetG.gain.setTargetAtTime(0.18 + n1 * 0.55, t, tc)
    // Quieter and duller from the flight deck than from outside.
    const engVol = (0.10 + n1 * 0.5) * (inside ? 0.55 : 1)
    this.eng.out.gain.setTargetAtTime(ac.crashed ? 0 : engVol, t, 0.15)

    // Airflow rises with indicated airspeed and with anything hanging out in it.
    const kt = ac.ias * 1.943844
    const drag = ac.gearPos * 0.35 + (ac.flapDeg / 40) * 0.3 + ac.spoilers * 0.3
    const airVol = clamp((kt - 40) / 320, 0, 1) * (0.22 + drag * 0.5) * (inside ? 0.7 : 1)
    this.air.out.gain.setTargetAtTime(airVol, t, tc)
    this.air.filter.frequency.setTargetAtTime(380 + kt * 5.5, t, tc)

    // Wheels. Only on the ground, and it grows with ground speed and braking.
    const gs = Math.hypot(ac.vel.x, ac.vel.z)
    const rollVol = ac.onGround ? clamp(gs / 70, 0, 1) * (0.28 + ac.brakes * 0.35) : 0
    this.roll.out.gain.setTargetAtTime(rollVol, t, 0.07)
    this.roll.filter.frequency.setTargetAtTime(90 + gs * 2.4, t, tc)

    // Stall warning: an intermittent tone, not a siren.
    if (ac.stalling && !ac.crashed) {
      this.warnPhase += dt
      const on = (this.warnPhase % 0.44) < 0.22
      this.warn.out.gain.setTargetAtTime(on ? 0.5 : 0, t, 0.01)
    } else {
      this.warnPhase = 0
      this.warn.out.gain.setTargetAtTime(0, t, 0.03)
    }

    // Overspeed clacker, the one warning that really does clack.
    if (ac.overspeed && !ac.crashed) {
      this.clackPhase += dt
      if (this.clackPhase > 0.14) {
        this.clackPhase = 0
        this.blip(1500 + Math.random() * 200, 0.035, 'square', 0.10)
      }
    }
  }

  suspend() { if (this.ctx && this.ctx.state === 'running') this.ctx.suspend() }
  resume() { if (this.ctx && this.enabled && this.ctx.state === 'suspended') this.ctx.resume() }
}
